/** Module registry — sidebar entries and README section mappings */
window.LLP_MODULES = [
  { title: "Window Overview & Utilities", sections: "1", keywords: "window overview tabs open lighting settings light explorer render pipeline asset", textOnly: true },
  { title: "Scene Lights & Cluster", sections: "2", keywords: "scene lights refresh select all deselect sort cluster focus on off right click", textOnly: true },
  { title: "Studio Lighting", sections: "3", keywords: "studio lighting baseline layout gizmos settings asset intensity scale", image: "StudioLightingUI.png", imageAlt: "Studio Lighting tab interface" },
  { title: "Presets", sections: "5,7,17", keywords: "presets global fx animation pro cookies", image: "PresetsTabUI.png", imageAlt: "Presets tab interface" },
  { title: "Light Groups", sections: "4", keywords: "light groups grouping organization edit enabled", image: "LightGroupsUI.png", imageAlt: "Light groups interface" },
  { title: "FX & Settings: Basic", sections: "13", keywords: "fx settings basic settings intensity range shadows lightmap bake type", image: "FxAndSettingsBasicSettingsUI.png", imageAlt: "FX basic settings interface" },
  { title: "FX Presets", sections: "7", keywords: "fx settings presets section saved effect setups per light type", image: "FxAndSettingsPresetsUI.png", imageAlt: "FX and settings presets interface" },
  { title: "Gradual Effect", sections: "47", keywords: "gradual effect smooth transition intensity range behavior", image: "FxAndSettingsGradualEffectUI.png", imageAlt: "Gradual effect interface" },
  { title: "Strobe Effect", sections: "48", keywords: "strobe effect pulse flashing loop", image: "FxAndSettingsStrobeEffectUI.png", imageAlt: "Strobe effect interface" },
  { title: "Step Sequencer", sections: "49", keywords: "step sequencer timed states duration color", image: "FxAndSettingsStepSequencerUI.png", imageAlt: "Step sequencer interface" },
  { title: "Color Switcher", sections: "10", keywords: "color switcher forward reverse random gradient pattern", image: "FxAndSettingsColorSwitcherUI.png", imageAlt: "Color switcher interface" },
  { title: "Material Changer", sections: "12", keywords: "material changer realtime emission albedo", image: "FxAndSettingsMaterialChangerUI.png", imageAlt: "Material changer interface" },
  { title: "Sound Effect", sections: "50", keywords: "sound effect audio source sync light intensity", image: "FxAndSettingsSoundEffectUI.png", imageAlt: "Sound effect handler interface" },
  { title: "Sound Reactor", sections: "51", keywords: "sound reactor rms audio reactive amplitude", image: "FxAndSettingsSoundReactorUI.png", imageAlt: "Sound reactor interface" },
  { title: "Volumetrics (URP)", sections: "9", keywords: "volumetrics urp fog additional light", image: "FxAndSettingsVolumetricsUI.png", imageAlt: "Volumetrics controls interface" },
  { title: "PRO Cookies: Texture", sections: "43", keywords: "pro cookies texture layers blur motion", image: "ProCookiesTextureTabUI.png", imageAlt: "PRO Cookies texture tab interface" },
  { title: "PRO Cookies: Animated", sections: "44", keywords: "pro cookies animated custom render texture crt", image: "ProCookiesAnimatedTabUI.png", imageAlt: "PRO Cookies animated tab interface" },
  { title: "PRO Cookies: Video", sections: "45", keywords: "pro cookies video clip render texture", image: "ProCookiesVideoTabUI.png", imageAlt: "PRO Cookies video tab interface" },
  { title: "Animation: Firefly", sections: "52", keywords: "animation firefly movement", image: "AnimationTabFireflyUI.png", imageAlt: "Animation firefly tab interface" },
  { title: "Animation: Rotation", sections: "53", keywords: "animation rotation axis pingpong random", image: "AnimationTabRotatorUI.png", imageAlt: "Animation rotation tab interface" },
  { title: "Day-Night: Directional A", sections: "54", keywords: "day night directional cycle skybox", image: "DayNightCycleDirectionalUI01.png", imageAlt: "Day-night directional controls screenshot one" },
  { title: "Day-Night: Directional B", sections: "55", keywords: "day night sun colors intensity phases", image: "DayNightCycleDirectionalUI02.png", imageAlt: "Day-night directional controls screenshot two" },
  { title: "Day-Night: Moon", sections: "46,5", keywords: "moon cycle profile skybox moon quad billboard", image: "DayNightCycleMoonCycleUI.png", imageAlt: "Day-night moon cycle interface" },
];
