/** Roadmap items sourced from Discord #llp-roadmap */
window.LLP_ROADMAP = [
  // In Progress
  {
    date: "2026-07-06",
    dateLabel: "Jul 6, 2026",
    module: "General",
    title: "Updating for Unity 6.5",
    status: "in-progress",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Studio Lighting",
    title: "Modifiers for Lighting Composition (reworked)",
    status: "in-progress",
  },

  // Planned
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Volumes / Post Processing",
    title: "Volume profile updater (for day/night cycle)",
    status: "planned",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Volumes / Post Processing",
    title: "Post Processing Presets (for day/night cycle and non day/night cycle)",
    status: "planned",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Triggers & Events",
    title: "Proximity events and triggers",
    status: "planned",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Triggers & Events",
    title: "Conditions",
    status: "planned",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Triggers & Events",
    title: "Button triggers",
    status: "planned",
  },
  {
    date: "2024-04-08",
    dateLabel: "Apr 8, 2024",
    module: "FX & Settings",
    title: "Create one-shot versions of the same effects with event triggers",
    status: "planned",
  },

  // Scratched
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Studio Lighting",
    title: "HDRI Setup",
    status: "scratched",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Studio Lighting",
    title: "Additional Lighting Setups",
    status: "scratched",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Studio Lighting",
    title: "Improve Light Probe generation",
    status: "scratched",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Day / Night Cycle",
    title: "Add Lightmap Phases",
    status: "scratched",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Day / Night Cycle",
    title: "Add different skybox shaders and materials for dynamic weather",
    status: "scratched",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Day / Night Cycle",
    title: "Improve Skybox shader so it reflects a real sky with planets and/or stars",
    status: "scratched",
  },
  {
    date: "2025-07-25",
    dateLabel: "Jul 25, 2025",
    module: "Light Animator",
    title: "Add Light Splines as a new effect section",
    status: "scratched",
  },

  // Completed
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "General",
    title: "Port the asset to s&box",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "PRO Cookies",
    title: "Add additional Video Cookies",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "PRO Cookies",
    title: "Add additional Animated Cookies",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "PRO Cookies",
    title: "Add additional Texture Cookies",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Presets",
    title: "Add global presets",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Presets",
    title: "Add presets for Day Night Cycle",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Presets",
    title: "Add presets for Animation",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Presets",
    title: "Add presets for FX & Settings",
    status: "completed",
  },
  {
    date: "2026-07-05",
    dateLabel: "Jul 5, 2026",
    module: "Studio Lighting",
    title: "Overall improvements for Lighting Composition",
    status: "completed",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Day / Night Cycle",
    title: "Modify time sliders to tie time to directional light position & rotation",
    status: "completed",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Day / Night Cycle",
    title: "Lightmap Blending",
    status: "completed",
  },
  {
    date: "2026-07-09",
    dateLabel: "Jul 9, 2026",
    module: "Day / Night Cycle",
    title: "Skybox Shader improvements",
    status: "completed",
  },
  {
    date: "2025-08-26",
    dateLabel: "Aug 26, 2025",
    module: "FX & Settings",
    title: "Add color states to the Step Sequencer effect",
    status: "completed",
  },
  {
    date: "2025-08-26",
    dateLabel: "Aug 26, 2025",
    module: "FX & Settings",
    title: "Move Sound Reactor effect to the Sound Effects section",
    status: "completed",
  },
];
